<?xml version="1.0" encoding="utf-8"?><Database Name="forpractice" Class="LinqToSqlDataClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-85TMEMB\FORPRACTICE;Initial Catalog=forpractice;Integrated Security=True" SettingsObjectName="Note_App_with_Database.Properties.Settings" SettingsPropertyName="forpracticeConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Notas" Member="Notas">
    <Type Name="Nota">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Titulo" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Nota" Member="Nota1" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Hora" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="[Hora Archivado]" Member="Hora_Archivado" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="[Pendiente/Archivado]" Member="Pendiente_Archivado" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>